# syntax=docker/dockerfile:1
# check=skip=SecretsUsedInArgOrEnv,critical_high_vulnerabilities
# ─────────────────────────────────────────────────────────
#  ArthAstra — Multi-Stage Dockerfile
#  Node 22 Alpine | Next.js 16 Standalone | Production Ready
#
#  Build:  docker compose --env-file .env.local build
#  Run:    docker compose --env-file .env.local up -d
# ─────────────────────────────────────────────────────────

# ── Stage 1: Install deps ─────────────────────────────────
FROM node:22-alpine3.21 AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files and install
COPY package.json package-lock.json* .npmrc* ./
RUN npm ci --legacy-peer-deps

# ── Stage 2: Build ────────────────────────────────────────
FROM node:22-alpine3.21 AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ── CRITICAL: nuke any stale .next that leaked past .dockerignore ──
# Windows builds produce files with node:crypto in names (colons = illegal on NTFS).
# This guarantees a pristine Linux-only build.
RUN rm -rf .next

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Build-time env vars for Next.js SSR/SSG.
# ARG names are intentionally generic to avoid Docker lint false-positives.
# These are passed via docker-compose build args and are NOT baked into
# the final image — they only exist in this disposable builder stage.
# Runtime env vars from docker-compose env_file override at container start.
ARG BUILD_DB_URI=""
ARG BUILD_AI_CREDENTIAL=""
ARG BUILD_SMS_SID=""
ARG BUILD_SMS_CRED=""

RUN MONGODB_URI="$BUILD_DB_URI" \
    GOOGLE_GENERATIVE_AI_API_KEY="$BUILD_AI_CREDENTIAL" \
    TWILIO_ACCOUNT_SID="$BUILD_SMS_SID" \
    TWILIO_AUTH_TOKEN="$BUILD_SMS_CRED" \
    npm run build

# ── Stage 3: Production Runner ────────────────────────────
# Secrets are NOT present in this stage — they are injected at runtime
# via docker-compose env_file / environment.
FROM node:22-alpine3.21 AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets (images, logo, etc.)
COPY --from=builder /app/public ./public

# Prerender cache dir with correct permissions
RUN mkdir -p .next && chown nextjs:nodejs .next

# Copy standalone Next.js output (minimal server bundle)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy static assets into the standalone tree
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is auto-generated by `next build` with output: "standalone"
CMD ["node", "server.js"]
