# ─────────────────────────────────────────────────────────
#  ArthAstra — Multi-Stage Dockerfile
#  Node 22 Alpine | Next.js 16 Standalone | Production Ready
# ─────────────────────────────────────────────────────────

# ── Stage 1: Install deps ─────────────────────────────────
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files and install
COPY package.json package-lock.json* .npmrc* ./
RUN npm ci --legacy-peer-deps

# ── Stage 2: Build ────────────────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ── CRITICAL: nuke any stale .next that leaked past .dockerignore ──
# Windows builds produce files with node:crypto in names (colons = illegal on NTFS).
# This guarantees a pristine Linux-only build.
RUN rm -rf .next

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# Build args — baked in at build time for Next.js SSR/SSG.
# Default to empty so the image builds even without secrets
# (runtime env vars from docker-compose override these).
ARG MONGODB_URI=""
ARG GOOGLE_GENERATIVE_AI_API_KEY=""
ARG TWILIO_ACCOUNT_SID=""
ARG TWILIO_AUTH_TOKEN=""

ENV MONGODB_URI=$MONGODB_URI
ENV GOOGLE_GENERATIVE_AI_API_KEY=$GOOGLE_GENERATIVE_AI_API_KEY
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN

RUN npm run build

# ── Stage 3: Production Runner ────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets (images, logo, etc.)
COPY --from=builder /app/public ./public

# Prerender cache dir with correct permissions
RUN mkdir -p .next && chown nextjs:nodejs .next

# Copy standalone Next.js output (minimal server bundle)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy static assets into the standalone tree
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is auto-generated by `next build` with output: "standalone"
CMD ["node", "server.js"]
